### PR TITLE
phone inputs (onboarding, edit profile), schema migration

### PR DESCRIPTION
**Pull request by parkerdavis1**
Phew, a good amount of trial and error went into this one. I tried using [libphonenumber-js](https://www.npmjs.com/package/libphonenumber-js) and [react-phone-number-input](https://www.npmjs.com/package/react-phone-number-input) but they require 'controlled' inputs, complicating remix's form handling niceties in many ways. I tried rolling my own simple version but ran into complications that felt like surely someone has already solved this...

Finally landed on using [react-input-mask](https://www.npmjs.com/package/react-input-mask) for the phone inputs, adding auto-formatting and constraints for good UX and to ensure consistency and readability in the database. 

## Typescript Feedback wanted
I am getting a typescript error on `<InputMask/>` in `/forms.tsx`:
> JSX element type 'InputMask' does not have any construct or call signatures.ts(2604)
> 'InputMask' cannot be used as a JSX component.
> Its type 'typeof import("/Users/parkerdavis/projects/evs-fork/evs/node_modules/@types/react-input-mask/index")' is not a valid JSX element type.ts(2786)

## Form validation: 
The input masking will take care of constraining the input but in case javascript is disabled the validation is this regex `/\(?\d{3}\)?\s?-?\d{3}-?\d{4}/`
Regex is a pain to look at, so to summarize, generally it accepts phone numbers in these formats:
XXXXXXXXXX
(XXX) XXX-XXXX
(XXX)XXX-XXXX
XXX-XXX-XXXX

## Checklist for issue #32

- [x] Update the database User model to track phone numbers
- [x] Make a reusable input schema for phone number validation
- [x] Integrate input fields for phone numbers into the signup process
- [ ] Update the admin users table to display phone numbers
- [ ] Update volunteer info cards in the event management routes to display phone numbers

### CODE REVIEW

**Comment by benhsm** [comment]
I'm not completely sure why the compiler can't infer the type of the default import, but changing to a named import seems to resolve the type error: `import { ReactInputMask as InputMask } from 'react-input-mask'`. It might have something to do with the original library using cjs conventions.

**Comment by parkerdavis1** [comment]
Thanks I tried that and it seems to ‘fix’ the typescript linting issues but then it fails in the test environment. 

> SyntaxError: The requested module 'react-input-mask' does not provide an export named 'ReactInputMask'

Because the react-input-mask package is not actively maintained, I'm inclined to find alternative solutions (even though it works just fine except for the typescript issues). I’m really flummoxed that there isn’t a clear answer to the telephone input problem. I’ll look at all the other input masking packages again but it seems like every one has an issue that makes it less than ideal (not maintained, can’t use a custom input, needs to hook into useState). 
https://github.com/uNmAnNeR/imaskjs
https://github.com/JsDaddy/ngx-mask
https://github.com/Tinkoff/maskito


I’m about ready to give up on masking. It’ll have to be a standard ‘tel’ input that either 
1) only accepts 10 digits with no other characters, even though that will throw errors and create friction for people who put dashes, parens, or spaces in the field, which is annoying. 
2) it accepts the existing regex, then strips out all the non-digit characters before storing it in the database which can then be formatted when displayed elsewhere.

**Comment by benhsm** [comment]
The second type of fallback solution using zod transforms seems like the easiest and best thing we could do at the moment

**Comment by benhsm** [comment]
Responses I'm getting back suggest something you could try - make a controlled input field that is bound to a hidden input that behaves like a native form element. That might get us both the UX and semantics that we would want here. Let me know if you'd want to pair on something like that

**Comment by parkerdavis1** [comment]
How would you feel about getting this basic (no masks) implementation done and merged first? Before thinking about any more masking possibilities, I may undo the current input mask changes on this PR, edit the tests to include phone numbers to get them passing, and then mark this PR ready for review. 

Not sure how tidy you like keeping commits, this PR will have at least 5 commits once its done. Rather than rebase squashing I think it might be useful to have them for reference later.

**Comment by benhsm** [comment]
There may be a problem with how our CI pipeline is doing database caching; I'll be looking into this today

**Comment by benhsm** [comment]
Looks good to me, nice work as usual!

**Pull request merged**
