### PR TITLE
Prefix lock to private event titles

### PR DESCRIPTION
**Pull request by parkerdavis1**
Locks are prefixed to private event titles in the load function before rendering on the page.

Screenshot 2023-08-11 at 10 48 18 AM

### CODE REVIEW

**Comment by parkerdavis1** [comment]
This same idea could be applied to events that still need help vs events that are full for "at a glance" calendar feedback? 
🐎{Event Title that still has openings}?
Or the number of openings could be suffixed onto the title (probably only realistically visible in Agenda view)
{Event Title}(2 of 4 filled)
Thoughts @benhsm @gregv ?

**Comment by parkerdavis1** [comment]
The problem would be dynamically updating that data when the user volunteers for an event, filling one of the spots.

**Comment by parkerdavis1** [comment]
Actually hey, remix takes care of invalidating and updating the data automatically.

**Comment by gregv** [comment]
> This same idea could be applied to events that still need help vs events that are full for "at a glance" calendar feedback? 🐎{Event Title that still has openings}? Or the number of openings could be suffixed onto the title (probably only realistically visible in Agenda view) {Event Title}(2 of 4 filled) Thoughts @benhsm @gregv ?

Love that thought process @parkerdavis1  - I usually borrow/steal from Google icons - something like this would make a ton of sense: https://fonts.google.com/icons?icon.query=checked

- Full 
- Someone has signed up
- Empty
image

**Comment by parkerdavis1** [comment]
FYI @benhsm, the lock feature is indeed ready in case you wanted to merge before the meeting tomorrow. I'm not thrilled with the volunteer number indicators I've come up with so far. That can be a separate PR.

**Pull request merged**
